openapi: 3.0.0
info:
  title: api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/customer/{id}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/mCustomers'
      operationId: get-customer
      description: ''
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
components:
  schemas:
    mCustomer:
      title: mCustomer
      x-examples:
        example-1: {}
      type: object
      properties:
        id:
          type: string
          example: CUST00000000001
        lastName:
          type: string
          example: Meier
        firstName:
          type: string
          example: Heinz
        dateOfBirth:
          type: string
          format: date
      required:
        - id
        - lastName
        - firstName
        - dateOfBirth
    mCustomers:
      type: object
      title: mCustomers
      properties:
        customers:
          type: object
          properties:
            customer:
              $ref: '#/components/schemas/mCustomer'
            address:
              $ref: '#/components/schemas/mAddress'
            contact:
              $ref: '#/components/schemas/mContact'
    mAddress:
      title: mAddress
      type: object
      properties:
        id:
          type: string
        strasse:
          type: string
          example: Via Caplania
        hausNr:
          type: integer
          example: '13'
        hausNrZusatz:
          type: string
          example: A
        plz:
          type: string
          example: '7071'
        ort:
          type: string
          example: Laax
      required:
        - id
        - strasse
        - hausNr
        - plz
        - ort
    mContact:
      title: mContact
      type: object
      properties:
        mobilePhone:
          type: string
          example: +41 79 333 11 22
        email:
          type: string
          format: email
          example: hans.muster@bluewin.ch
      required:
        - email
