openapi: 3.0.0
info:
  title: api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/customer/{id}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/mCustomer'
      operationId: get-customer
      description: ''
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
components:
  schemas:
    mCustomer:
      title: mCustomer
      x-examples:
        example-1: {}
      type: object
      properties:
        id:
          type: string
          example: CUST00000000001
        lastName:
          type: string
          example: Meier
        firstName:
          type: string
          example: Heinz
        dateOfBirth:
          type: string
          format: date
      required:
        - id
        - lastName
        - firstName
        - dateOfBirth
