openapi: 3.0.0
info:
  title: api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /customer/:
    get:
      summary: Customer Interface
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/mCustomer'
        '204':
          description: No entitiy is found.
      operationId: get-customer
      description: 'Select a given Customer by ID. If the customer with ID does not exist, the service returns a http code 204 (no content) in the header and an empty body.'
      requestBody:
        content:
          application/xml:
            schema:
              type: object
              properties:
                operation:
                  $ref: '#/components/schemas/mOperation'
        description: ''
    parameters: []
    post:
      summary: Create a new Customer
      operationId: 'post-customer-{id}'
      responses:
        '200':
          description: OK
      description: Create a non-existing Customer
      requestBody:
        content:
          application/xml:
            schema:
              type: object
              properties:
                person:
                  $ref: '#/components/schemas/mPerson'
                addressId:
                  $ref: '#/components/schemas/mId'
                loginId:
                  $ref: '#/components/schemas/mId'
                contactId:
                  $ref: '#/components/schemas/mId'
              required:
                - person
                - addressId
                - loginId
                - contactId
        description: All Ids must be present in order to create a new Customer. Does that work for you?
components:
  schemas:
    mPerson:
      title: mPerson
      x-examples:
        example-1: {}
      type: object
      properties:
        lastName:
          type: string
          example: Meier
        firstName:
          type: string
          example: Heinz
        dateOfBirth:
          type: string
          format: date
        salutation:
          type: string
          example: Herr
        id:
          $ref: '#/components/schemas/mId'
      required:
        - lastName
        - firstName
        - dateOfBirth
        - salutation
      description: Represents a person. A person might be a customer or an employee
    mAddress:
      title: mAddress
      type: object
      properties:
        strasse:
          type: string
          example: Via Caplania
        hausNr:
          type: integer
          example: '13'
        hausNrZusatz:
          type: string
          example: A
        plz:
          type: string
          example: '7071'
        ort:
          type: string
          example: Laax
        id:
          $ref: '#/components/schemas/mId'
      required:
        - strasse
        - hausNr
        - plz
        - ort
      description: Represents an address in Switzerland.
    mContact:
      title: mContact
      type: object
      properties:
        mobilePhone:
          type: string
          example: +41 79 333 11 22
        email:
          type: string
          format: email
          example: hans.muster@bluewin.ch
        id:
          $ref: '#/components/schemas/mId'
      required:
        - email
      description: 'Represents contact information. So far, mobilePhone and email address are taken into account.'
    mCustomer:
      type: object
      title: mCustomers
      properties:
        customer:
          type: object
          properties:
            person:
              $ref: '#/components/schemas/mPerson'
            address:
              $ref: '#/components/schemas/mAddress'
            contact:
              $ref: '#/components/schemas/mContact'
            login:
              $ref: '#/components/schemas/mLogin'
            credit:
              $ref: '#/components/schemas/mCredit'
      description: 'Represents a customer. On this interface a customer is made up by different eintity types, such as address, login and so on.'
    mLogin:
      title: mLogin
      type: object
      properties:
        username:
          type: string
          example: schnemac
        secret:
          type: string
          example: c03dc1575140c6d59a8cea5cf0828ac7
        id:
          $ref: '#/components/schemas/mId'
      required:
        - username
        - secret
      description: Represents a Login. A login might be related to a customer or an employee.
    mCredit:
      title: mCredit
      type: object
      properties:
        cardHolderName:
          type: string
          example: Max Muster
        institute:
          type: string
          example: VISA
        cardNumber:
          type: string
          example: 1234 4321 5678 8765
        id:
          $ref: '#/components/schemas/mId'
      required:
        - cardHolderName
        - institute
        - cardNumber
      description: Represents a credit card.
    mId:
      type: string
      title: mId
      example: ENT000000000001
      description: 'Represents an ID. The ID is otpional, but must be present in all Responses. The ID must not be present in a POST operation, but must be present in a PUT operation. On the interface, the ID is represented by a String. The ID might be a number datatatype in the backend however.'
    mOperation:
      title: mOperation
      type: object
      properties:
        status:
          $ref: '#/components/schemas/mOperationStatus'
        entity:
          $ref: '#/components/schemas/mId'
    mOperationStatus:
      title: mOperationStatus
      type: object
      properties:
        success:
          type: boolean
        errorCode:
          type: string
        errorMessage:
          type: string
